# Load packages import counts raw
library(stringr)
library(dplyr)
library(tidyr)

library(ggplot2)
library(Seurat)
library(gridExtra)
library(grid)
library(kableExtra)
library(matrixStats)
library(ggthemes)
library(sctransform)
library(ggsci)
library(viridis)
library(RColorBrewer)
library(patchwork)
library(sctransform)
library(extrafont) # run once in system font_import() loadfonts()
library(MOFA2)
library(scico)
library(ggpubr)
library(ggrepel)
library(ggcorrplot)
library(ggplotify)
library(ggtext)
library(cowplot)
library(magick)

library('org.Hs.eg.db')
library('enrichplot')
library(clusterProfiler.dplyr)
library(clusterProfiler)
library(forcats)

library(png)
