---
title: "revisions"
author: "Jessie van Buggenum"
date: "2021-04-20"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, warning=FALSE, message=FALSE}
source("code/load_packages.R")
seu_combined_selectsamples <- readRDS("output/seu_aIG_samples.rds")


panellabels <- c('a', 'b', 'c','d' , 'e', 'f', 'g', 'h', 'i', 'j', 'k')

add.textsize <- theme(axis.text.x = element_text(colour = 'black', size = 7),
          axis.text.y = element_text(colour = 'black',size=7),
          text = element_text(size=7),
          axis.text=element_text(size=7),
          plot.title = element_text(size=7)
          )


colorgradient6_manual <- c("#F7FBFF","#CFE1F2", "#93C4DE", "#4A97C9", "#1F5284", "#0C2236" )
colorgradient6_manual2 <- c("#d4d4d3","#CFE1F2", "#93C4DE", "#4A97C9", "#1F5284", "#0C2236" )
labels <- c("0", "2", "4", "6", "60", "180")

```

## p-JAK high vs low

```{r}
proteindata_counts <- as.data.frame(t(seu_combined_selectsamples@assays$PROT@scale.data)) %>%
  mutate(sample = rownames(t(seu_combined_selectsamples@assays$PROT@scale.data)))


metadata.all <- as.data.frame(seu_combined_selectsamples@meta.data) %>%
  mutate(sample = rownames((seu_combined_selectsamples@meta.data)))

proteindata_counts <- left_join(proteindata_counts, metadata.all)



toppJAK1 <- proteindata_counts %>%
  group_by(time) %>%
  top_frac(wt = `p-JAK1`, n = 0.05)

bottompJAK1 <- proteindata_counts %>%
  group_by(time) %>%
  top_frac(wt = `p-JAK1`, n = -0.05)

proteindata_counts <- proteindata_counts %>%
  mutate(highlowpJAK1 = ifelse(sample %in% toppJAK1$sample, "p-JAK1 high", ifelse(sample %in% bottompJAK1$sample, "p-JAK1 low","middle")))

addmeta <- proteindata_counts[,c("highlowpJAK1", "sample")]
rownames(addmeta) <- proteindata_counts$sample

seu_combined_selectsamples <- AddMetaData(seu_combined_selectsamples, addmeta)
```




### 180 minutes

```{r}
seu.JAK1.180 <- subset(seu_combined_selectsamples, condition == "180.aIg.contr" & highlowpJAK1 != "middle")

seu.JAK1.180 <- SetIdent(seu.JAK1.180, value = "highlowpJAK1")

```

```{r}
VlnPlot(seu.JAK1.180,assay = "PROT", features =  c("p-JAK1","nCount_PROT", "nCount_RNA"), group.by = "highlowpJAK1",ncol = 3)
```

```{r, error=FALSE}
# Find differentially expressed features between CD14+ and FCGR3A+ Monocytes
markers.180 <- FindMarkers(seu.JAK1.180,ident.1 = "p-JAK1 high", ident.2 = "p-JAK1 low", assay = "PROT", slot = "scale.data", logfc.threshold = 0, return.thresh = 1, only.pos = F)
# view results
#markers.180 <- filter(markers.180, cluster == "p-JAK1 high")
#markers.180


# Find differentially expressed features between CD14+ and FCGR3A+ Monocytes
markers.180.RNA <-  FindAllMarkers(seu.JAK1.180,assay = "RNA", slot = "data", logfc.threshold = 0.3, return.thresh = 0.01, only.pos = T,min.pct = 0.1)
markers.180.RNA <-   FindMarkers(seu.JAK1.180,ident.1 = "p-JAK1 high", ident.2 = "p-JAK1 low", assay = "SCT.RNA", slot = "scale.data", logfc.threshold = 0, return.thresh = 1, only.pos = F)
# view results
#markers.180.RNA

```

#### Protein

```{r, fig.width=4, fig.height=4, warning=FALSE}
library(ggrepel)
markers.180$protein <-rownames(markers.180)
# add a column of NAs
markers.180$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
markers.180$diffexpressed[markers.180$avg_diff > 0.25 & markers.180$p_val_adj < 0.01] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
markers.180$diffexpressed[markers.180$avg_diff  < -0.25 & markers.180$p_val_adj < 0.01] <- "DOWN"

mycolors <- c("blue", "red", "black")
names(mycolors) <- c("DOWN", "UP", "NO")


markers.180$delabel <- NA
markers.180$delabel[markers.180$diffexpressed != "NO"] <- markers.180$protein[markers.180$diffexpressed != "NO"]

# Finally, we can organize the labels nicely using the "ggrepel" package and the geom_text_repel() function
# load library
library(ggrepel)
# plot adding up all layers we have seen so far
plot.vulcano.180min <- ggplot(data=markers.180, aes(x=avg_diff , y=-log10(p_val_adj), col=diffexpressed, label=delabel)) +
        geom_point(size=0.5) + 
        theme_minimal() +
        geom_text_repel(size=2.2) +
        scale_color_manual(values=c("blue", "red", "black")) +
        geom_vline(xintercept=c(-0.25, 0.25), col="red") +
        geom_hline(yintercept=-log10(0.01), col="red") +
  labs(x = expression("Log"[2]*" Fold Change"), y = expression("-log"[10]*" adjusted p-value"), title = "p-JAK1 high vs p-JAK1 low (t = 180 min)") &
  add.textsize
plot.vulcano.180min

```

```{r, fig.width=16, fig.height=4, warning=FALSE}
sign.markers180 <- markers.180$protein[markers.180$avg_diff > 0.25 & markers.180$p_val_adj < 0.01 | markers.180$avg_diff  < -0.25 & markers.180$p_val_adj < 0.01] 

plot.vln.180min <- VlnPlot(seu.JAK1.180,assay = "PROT",slot = "scale.data", features =  sign.markers180, group.by = "highlowpJAK1",ncol = 6, pt.size = 0.5) &
  add.textsize
plot.vln.180min 
```

#### RNA

```{r, warning=FALSE}
library(ggrepel)
markers.180.RNA$protein <-rownames(markers.180.RNA)
# add a column of NAs
markers.180.RNA$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
markers.180.RNA$diffexpressed[markers.180.RNA$avg_diff > 0.25 & markers.180.RNA$p_val < 0.05] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
markers.180.RNA$diffexpressed[markers.180.RNA$avg_diff < -0.25 & markers.180.RNA$p_val < 0.05] <- "DOWN"

mycolors <- c("blue", "red", "black")
names(mycolors) <- c("DOWN", "UP", "NO")


markers.180.RNA$delabel <- NA
markers.180.RNA$delabel[markers.180.RNA$diffexpressed != "NO"] <- markers.180.RNA$protein[markers.180.RNA$diffexpressed != "NO"]

# Finally, we can organize the labels nicely using the "ggrepel" package and the geom_text_repel() function
# load library
library(ggrepel)
# plot adding up all layers we have seen so far
plot.vulcano.180min.RNA <- ggplot(data=markers.180.RNA, aes(x=avg_diff, y=-log10(p_val), col=diffexpressed, label=delabel)) +
        geom_point() + 
        theme_minimal() +
        geom_text_repel(size=2.2) +
        scale_color_manual(values=c("blue", "red", "black")) +
        geom_vline(xintercept=c(-0.25, 0.25), col="red") +
        geom_hline(yintercept=-log10(0.05), col="red") +
  labs(x = expression("Log"[2]*" Fold Change"), y = expression("-log"[10]*" p-value"), title = "p-JAK1 high vs p-JAK1 low (t = 180 min)") &
  add.textsize
plot.vulcano.180min.RNA

```

```{r, fig.width=16, fig.height=8}
sign.markers180.RNA <- markers.180.RNA$protein[markers.180.RNA$avg_diff > 0.25 & markers.180.RNA$p_val < 0.05] 

plot.vln.180min.RNA <- VlnPlot(seu.JAK1.180,assay = "RNA", features =  sign.markers180.RNA[1:20], group.by = "highlowpJAK1",ncol = 10) &
  add.textsize
plot.vln.180min.RNA 
```

#### plot 180 min prot

```{r plot_180min, fig.width=7.2, fig.height=3}

plot_180min <- plot_grid(plot.vulcano.180min, plot.vln.180min, labels = panellabels[c(5,6)], label_size = 10, ncol = 2, rel_widths = c(1,2))

#ggsave(plot_180min, filename = "output/paper_figures/Fig2.pdf", width = 183, height = 183, units = "mm",  dpi = 300, useDingbats = FALSE)
#ggsave(plot_180min, filename = "output/paper_figures/Fig2.png", width = 183, height = 183, units = "mm",  dpi = 300)

plot_180min
```




### 006 minutes

```{r}
seu.JAK1.006 <- subset(seu_combined_selectsamples, condition == "006.aIg.contr" & highlowpJAK1 != "middle")

seu.JAK1.006 <- SetIdent(seu.JAK1.006, value = "highlowpJAK1")

```

```{r}
VlnPlot(seu.JAK1.006,assay = "PROT", features =  c("p-JAK1","nCount_PROT", "nCount_RNA"), group.by = "highlowpJAK1",ncol = 3)
```

```{r, error=FALSE}
# Find differentially expressed features between CD14+ and FCGR3A+ Monocytes
markers.006 <- FindMarkers(seu.JAK1.006,ident.1 = "p-JAK1 high", ident.2 = "p-JAK1 low", assay = "PROT", slot = "scale.data", logfc.threshold = 0, return.thresh = 1, only.pos = F)
# view results
#markers.006 <- filter(markers.006, cluster == "p-JAK1 high")
#markers.006


# Find differentially expressed features between CD14+ and FCGR3A+ Monocytes
markers.006.RNA <-  FindAllMarkers(seu.JAK1.006,assay = "RNA", slot = "data", logfc.threshold = 0.3, return.thresh = 0.01, only.pos = T,min.pct = 0.1)
markers.006.RNA <-   FindMarkers(seu.JAK1.006,ident.1 = "p-JAK1 high", ident.2 = "p-JAK1 low", assay = "SCT.RNA", slot = "scale.data", logfc.threshold = 0, return.thresh = 1, only.pos = F)
# view results
#markers.006.RNA

```

#### Protein

```{r, fig.width=4, fig.height=4, warning=FALSE}
library(ggrepel)
markers.006$protein <-rownames(markers.006)
# add a column of NAs
markers.006$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
markers.006$diffexpressed[markers.006$avg_diff > 0.25 & markers.006$p_val_adj < 0.01] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
markers.006$diffexpressed[markers.006$avg_diff  < -0.25 & markers.006$p_val_adj < 0.01] <- "DOWN"

mycolors <- c("blue", "red", "black")
names(mycolors) <- c("DOWN", "UP", "NO")


markers.006$delabel <- NA
markers.006$delabel[markers.006$diffexpressed != "NO"] <- markers.006$protein[markers.006$diffexpressed != "NO"]

# Finally, we can organize the labels nicely using the "ggrepel" package and the geom_text_repel() function
# load library
library(ggrepel)
# plot adding up all layers we have seen so far
plot.vulcano.006min <- ggplot(data=markers.006, aes(x=avg_diff , y=-log10(p_val_adj), col=diffexpressed, label=delabel)) +
        geom_point(size=0.5) + 
        theme_minimal() +
        geom_text_repel(size=2.2) +
        scale_color_manual(values=c("blue", "red", "black")) +
        geom_vline(xintercept=c(-0.25, 0.25), col="red") +
        geom_hline(yintercept=-log10(0.01), col="red") +
  labs(x = expression("Log"[2]*" Fold Change"), y = expression("-log"[10]*" adjusted p-value"), title = "p-JAK1 high vs p-JAK1 low (t = 006 min)") &
  add.textsize
plot.vulcano.006min

```

```{r, fig.width=16, fig.height=4, warning=FALSE}
sign.markers006 <- markers.006$protein[markers.006$avg_diff > 0.25 & markers.006$p_val_adj < 0.01 | markers.006$avg_diff  < -0.25 & markers.006$p_val_adj < 0.01] 

plot.vln.006min <- VlnPlot(seu.JAK1.006,assay = "PROT",slot = "scale.data", features =  sign.markers006, group.by = "highlowpJAK1",ncol = 6, pt.size = 0.5) &
  add.textsize
plot.vln.006min 
```

#### RNA

```{r, warning=FALSE}
library(ggrepel)
markers.006.RNA$protein <-rownames(markers.006.RNA)
# add a column of NAs
markers.006.RNA$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
markers.006.RNA$diffexpressed[markers.006.RNA$avg_diff > 0.25 & markers.006.RNA$p_val < 0.05] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
markers.006.RNA$diffexpressed[markers.006.RNA$avg_diff < -0.25 & markers.006.RNA$p_val < 0.05] <- "DOWN"

mycolors <- c("blue", "red", "black")
names(mycolors) <- c("DOWN", "UP", "NO")


markers.006.RNA$delabel <- NA
markers.006.RNA$delabel[markers.006.RNA$diffexpressed != "NO"] <- markers.006.RNA$protein[markers.006.RNA$diffexpressed != "NO"]

# Finally, we can organize the labels nicely using the "ggrepel" package and the geom_text_repel() function
# load library
library(ggrepel)
# plot adding up all layers we have seen so far
plot.vulcano.006min.RNA <- ggplot(data=markers.006.RNA, aes(x=avg_diff, y=-log10(p_val), col=diffexpressed, label=delabel)) +
        geom_point() + 
        theme_minimal() +
        geom_text_repel(size=2.2) +
        scale_color_manual(values=c("blue", "red", "black")) +
        geom_vline(xintercept=c(-0.25, 0.25), col="red") +
        geom_hline(yintercept=-log10(0.05), col="red") +
  labs(x = expression("Log"[2]*" Fold Change"), y = expression("-log"[10]*" p-value"), title = "p-JAK1 high vs p-JAK1 low (t = 006 min)") &
  add.textsize
plot.vulcano.006min.RNA

```

```{r, fig.width=16, fig.height=8}
sign.markers006.RNA <- markers.006.RNA$protein[markers.006.RNA$avg_diff > 0.25 & markers.006.RNA$p_val < 0.05] 

plot.vln.006min.RNA <- VlnPlot(seu.JAK1.006,assay = "RNA", features =  sign.markers006.RNA[1:20], group.by = "highlowpJAK1",ncol = 10) &
  add.textsize
plot.vln.006min.RNA 
```

#### plot 006 min prot

```{r plot_006min, fig.width=7.2, fig.height=3}

plot_006min <- plot_grid(plot.vulcano.006min, plot.vln.006min, labels = panellabels[c(3,4)], label_size = 10, ncol = 2, rel_widths = c(1,2))

#ggsave(plot_006min, filename = "output/paper_figures/Fig2.pdf", width = 183, height = 183, units = "mm",  dpi = 300, useDingbats = FALSE)
#ggsave(plot_006min, filename = "output/paper_figures/Fig2.png", width = 183, height = 183, units = "mm",  dpi = 300)

plot_006min
```


### 002 minutes

```{r}
seu.JAK1.002 <- subset(seu_combined_selectsamples, condition == "002.aIg.contr" & highlowpJAK1 != "middle")

seu.JAK1.002 <- SetIdent(seu.JAK1.002, value = "highlowpJAK1")

```

```{r}
VlnPlot(seu.JAK1.002,assay = "PROT", features =  c("p-JAK1","nCount_PROT", "nCount_RNA"), group.by = "highlowpJAK1",ncol = 3)
```

```{r, error=FALSE}
# Find differentially expressed features between CD14+ and FCGR3A+ Monocytes
markers.002 <- FindMarkers(seu.JAK1.002,ident.1 = "p-JAK1 high", ident.2 = "p-JAK1 low", assay = "PROT", slot = "scale.data", logfc.threshold = 0, return.thresh = 1, only.pos = F)
# view results
#markers.002 <- filter(markers.002, cluster == "p-JAK1 high")
#markers.002


# Find differentially expressed features between CD14+ and FCGR3A+ Monocytes
markers.002.RNA <-  FindAllMarkers(seu.JAK1.002,assay = "RNA", slot = "data", logfc.threshold = 0.3, return.thresh = 0.01, only.pos = T,min.pct = 0.1)
markers.002.RNA <-   FindMarkers(seu.JAK1.002,ident.1 = "p-JAK1 high", ident.2 = "p-JAK1 low", assay = "SCT.RNA", slot = "scale.data", logfc.threshold = 0, return.thresh = 1, only.pos = F)
# view results
#markers.002.RNA

```

#### Protein

```{r, fig.width=4, fig.height=4, warning=FALSE}
library(ggrepel)
markers.002$protein <-rownames(markers.002)
# add a column of NAs
markers.002$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
markers.002$diffexpressed[markers.002$avg_diff > 0.25 & markers.002$p_val_adj < 0.01] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
markers.002$diffexpressed[markers.002$avg_diff  < -0.25 & markers.002$p_val_adj < 0.01] <- "DOWN"

mycolors <- c("blue", "red", "black")
names(mycolors) <- c("DOWN", "UP", "NO")


markers.002$delabel <- NA
markers.002$delabel[markers.002$diffexpressed != "NO"] <- markers.002$protein[markers.002$diffexpressed != "NO"]

# Finally, we can organize the labels nicely using the "ggrepel" package and the geom_text_repel() function
# load library
library(ggrepel)
# plot adding up all layers we have seen so far
plot.vulcano.002min <- ggplot(data=markers.002, aes(x=avg_diff , y=-log10(p_val_adj), col=diffexpressed, label=delabel)) +
        geom_point(size=0.5) + 
        theme_minimal() +
        geom_text_repel(size=2.2) +
        scale_color_manual(values=c("blue", "red", "black")) +
        geom_vline(xintercept=c(-0.25, 0.25), col="red") +
        geom_hline(yintercept=-log10(0.01), col="red") +
  labs(x = expression("Log"[2]*" Fold Change"), y = expression("-log"[10]*" adjusted p-value"), title = "p-JAK1 high vs p-JAK1 low (t = 002 min)") &
  add.textsize
plot.vulcano.002min

```

```{r, fig.width=16, fig.height=4, warning=FALSE}
sign.markers002 <- markers.002$protein[markers.002$avg_diff > 0.25 & markers.002$p_val_adj < 0.01 | markers.002$avg_diff  < -0.25 & markers.002$p_val_adj < 0.01] 

plot.vln.002min <- VlnPlot(seu.JAK1.002,assay = "PROT",slot = "scale.data", features =  sign.markers002, group.by = "highlowpJAK1",ncol = 6, pt.size = 0.5) &
  add.textsize
plot.vln.002min 
```

#### RNA

```{r, warning=FALSE}
library(ggrepel)
markers.002.RNA$protein <-rownames(markers.002.RNA)
# add a column of NAs
markers.002.RNA$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
markers.002.RNA$diffexpressed[markers.002.RNA$avg_diff > 0.25 & markers.002.RNA$p_val < 0.05] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
markers.002.RNA$diffexpressed[markers.002.RNA$avg_diff < -0.25 & markers.002.RNA$p_val < 0.05] <- "DOWN"

mycolors <- c("blue", "red", "black")
names(mycolors) <- c("DOWN", "UP", "NO")


markers.002.RNA$delabel <- NA
markers.002.RNA$delabel[markers.002.RNA$diffexpressed != "NO"] <- markers.002.RNA$protein[markers.002.RNA$diffexpressed != "NO"]

# Finally, we can organize the labels nicely using the "ggrepel" package and the geom_text_repel() function
# load library
library(ggrepel)
# plot adding up all layers we have seen so far
plot.vulcano.002min.RNA <- ggplot(data=markers.002.RNA, aes(x=avg_diff, y=-log10(p_val), col=diffexpressed, label=delabel)) +
        geom_point() + 
        theme_minimal() +
        geom_text_repel(size=2.2) +
        scale_color_manual(values=c("blue", "red", "black")) +
        geom_vline(xintercept=c(-0.25, 0.25), col="red") +
        geom_hline(yintercept=-log10(0.05), col="red") +
  labs(x = expression("Log"[2]*" Fold Change"), y = expression("-log"[10]*" p-value"), title = "p-JAK1 high vs p-JAK1 low (t = 002 min)") &
  add.textsize
plot.vulcano.002min.RNA

```

```{r, fig.width=16, fig.height=8}
sign.markers002.RNA <- markers.002.RNA$protein[markers.002.RNA$avg_diff > 0.25 & markers.002.RNA$p_val < 0.05] 

plot.vln.002min.RNA <- VlnPlot(seu.JAK1.002,assay = "RNA", features =  sign.markers002.RNA[1:20], group.by = "highlowpJAK1",ncol = 10) &
  add.textsize
plot.vln.002min.RNA 
```

#### plot 002 min prot

```{r plot_002min, fig.width=7.2, fig.height=3}

plot_002min <- plot_grid(plot.vulcano.002min, plot.vln.002min, labels = panellabels[c(1,2)], label_size = 10, ncol = 2, rel_widths = c(1,2))

#ggsave(plot_002min, filename = "output/paper_figures/Fig2.pdf", width = 183, height = 183, units = "mm",  dpi = 300, useDingbats = FALSE)
#ggsave(plot_002min, filename = "output/paper_figures/Fig2.png", width = 183, height = 183, units = "mm",  dpi = 300)

plot_002min
```

## gather plot
```{r plot_all, fig.width=7.2, fig.height=7.2}

plot_all <- plot_grid(plot_002min,plot_006min,plot_180min , labels =c("", "", ""), ncol = 1, rel_heights = c(1,1,1))

ggsave(plot_all, filename = "output/paper_figures/Suppl_pJAK1_highlow.pdf", width = 183, height = 140, units = "mm",  dpi = 300, useDingbats = FALSE)
ggsave(plot_all, filename = "output/paper_figures/Suppl_pJAK1_highlow.png", width = 183, height = 140, units = "mm",  dpi = 300)

plot_all
```



